### ISSUE TITLE
PDOS: adding an optional copying of the wavefunction file

### ISSUE THREAD

**Issue by dpasserone** [nanotech-empa/aiidalab-empa-scanning-probe#19]
Dear developers, in the app PDOS it would be great to add a checkbox to allow the user to import/not import the wavefunction from the PK that refers to the selected structure. This because the PDOS requires a diagonalization that often profits from a previous OT wavefunction. This is useful in some cases of difficult convergence, which happened to me with a spin-polarized ribbon on a metal surface (@eimrek private communication)

In case the WF is not found (too old PK, WF not stored), then there a message should appear:

"You checked the wavefunction restart. Since wfn is not available, a preliminary OT optimization with threshold 1E-5 will be performed before diagonalization" 

and an additional run should be done (OT, maybe with loose convergence threshold) before the actual PDOS. 

Thank you.

**Comment by yakutovicha** [comment]
@cpinedoli, can you please comment on this?

**Comment by dpasserone** [comment]
> 

Is @cpignedoli not pinedoli :-)

**Comment by cpignedoli** [comment]
The restart from an available wfn should be already available for  RKS following what was done for NEB.
For UKS cases, we need support from CP2K experts in this class of simulations.

Priority would be:
-define a strong protocol to get a properly converged UKS wfn as we tried for the GW app
-use this protocol as the first step every time we have UKS calculations
-adapt the protocol to cases where an initial wfn is available
- @eimrek can you further comment?

Here design decisions must be taken: e.g. how do we show/check at PDOS submission what was the initial guess or multiplicity used in the available calculation?

**Comment by eimrek** [comment]
The code to use the .wfn file is there and automatically used for an RKS calculation. I disabled for UKS calculations as otherwise the spin guess is ignored. This didn't cause problems in my calculations, but I think Daniele is running very big systems that benefit from a wfn file. Best solution probably would be to have a checkbox that controls this behavior, as Daniele described.

In the case of GW, it's very important not to get a negative gap, and there needs to be a multiple checks for that. Something similar can be used here but with the goal of speeding up the calculation, I suppose.

Regarding how to see in the visualization interface what spin solution was obtained: i think the best solution is to visualize a top-down rendered spin-density in the interface. (together with input multiplicity and magnetization values).

**Comment by cpignedoli** [comment]
@yakutovicha  I would consider this closed since now we first do an OT step by default (and we check if a wfn was available) and we do a diag afterwards (the user decides whether it will be selfconsistent diag or not)

**Comment by yakutovicha** [comment]
> @yakutovicha I would consider this closed since now we first do an OT step by default (and we check if a wfn was available) and we do a diag afterwards (the user decides whether it will be selfconsistent diag or not)

sounds good!
